name: Docker Build and Update Manifest

on:
  push:
    branches:
      - master

jobs: 
  setup-env:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

  version-identifier:
    runs-on: ubuntu-latest
    steps:
      - name: set version identifier
        run: echo "VERSION_IDENTIFIER=0.1.${GITHUB_RUN_NUMBER}_${GITHUB_RUN_ATTEMPT}_${GITHUB_SHA:0:7}" | tee $GITHUB_ENV
    outputs:
      version_identifier: ${{ env.VERSION_IDENTIFIER }}

  docker_publish:
    uses: dangi13/workflows/.github/workflows/docker-publish.yml@v6
    with:
      image_tag: ${{ needs.version-identifier.outputs.version_identifier }} 
      image_name: docker.pkg.github.com/dangi13/web-crawler/crawler

  update_manifest:
    needs: docker_publish
    uses: dangi13/workflows/.github/workflows/update-manifest.yml@v6
    secrets: inherit
    with:
      version: ${{ needs.version-identifier.outputs.version_identifier }}
      repository_name: ${{ github.event.repository.name }}
      
