name: Docker Build and Update Manifest

on:
  push:
    branches:
      - master

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

  generate_version_id:
    uses: dangi13/workflows/.github/workflows/version-identifier.yml@v6

  docker_publish:
    needs: generate_version_id
    uses: dangi13/workflows/.github/workflows/docker-publish.yml@v6
    with:
      image_tag: ${{ fromJson(needs.generate_version_id.outputs.version_identifier) }} 
      image_name: docker.pkg.github.com/dangi13/web-crawler/crawler

  update_manifest:
    uses: dangi13/workflows/.github/workflows/update-manifest.yml@v6
    needs: generate_version_id
    secrets: inherit
    with:
      version: ${{ fromJson(needs.generate_version_id.outputs.version_identifier) }}
      repository_name: ${{ github.event.repository.name }}
      
