name: Docker Build and Update Manifest

on:
  push:
    branches:
      - master

jobs: 
  version_identifier:
    runs-on: ubuntu-latest
    steps:
      - name: set version identifier
        run: echo "VERSION_IDENTIFIER=0.1.${GITHUB_RUN_NUMBER}_${GITHUB_RUN_ATTEMPT}_${GITHUB_SHA:0:7}" | tee $GITHUB_ENV
    outputs:
      version_identifier: ${{ env.VERSION_IDENTIFIER }}
   
  docker_publish:
    needs: version_identifier
    uses: dangi13/workflows/.github/workflows/docker-publish.yml@v9
    with:
      image_tag: ${{ needs.version_identifier.outputs.version_identifier }} 
      image_name: docker.pkg.github.com/dangi13/web-crawler/crawler

  update_manifest:
    needs: [docker_publish, version_identifier]
    uses: dangi13/workflows/.github/workflows/update-manifest.yml@v10
    secrets: inherit
    with:
      version: ${{ needs.version_identifier.outputs.version_identifier }}
      repository_name: ${{ github.event.repository.name }}
      
