name: Docker Build and Update Manifest

on:
  push:
    branches:
      - master

jobs: 
  version-identifier:
   uses: dangi13/workflows/.github/workflows/version-identifier.yml@v9
   
  docker_publish:
    needs: version-identifier
    uses: dangi13/workflows/.github/workflows/docker-publish.yml@v9
    with:
      image_tag: ${{ needs.version-identifier.outputs.version_identifier }} 
      image_name: docker.pkg.github.com/dangi13/web-crawler/crawler

  update_manifest:
    needs: [docker_publish, version-identifier]
    uses: dangi13/workflows/.github/workflows/update-manifest.yml@v9
    secrets: inherit
    with:
      version: ${{ needs.version-identifier.outputs.version_identifier }}
      repository_name: ${{ github.event.repository.name }}
      
