name: Docker Build and Update Manifest file

on:
  push:
    branches:
      - master 

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Get latest commit hash
        run: |
          echo "::set-output name=short_commit_hash::$(git rev-parse --short HEAD)"
      - name: Read commit hash
        id: read_commit_hash
        uses: actions/github-script@v6
        with:
          script: |
            return core.getInput('path'); 
          path: short_commit_id.txt

      - name: Checkout releases repo
        uses: actions/checkout@v3
        with:
          repository: dangi13/releases
          ref: main
          persist-credentials: false 
          token: ${{ secrets.PAT }}

      - name: Update dev.json
        run: |
          major_version=$(echo "${{ github.ref }}" | cut -d '.' -f 1)
          minor_version=$(echo "${{ github.ref }}" | cut -d '.' -f 2)
          build_id=$(date +%s)
          short_commit_id="${{ steps.get_commit_hash.outputs.short_commit_hash }}" 
          new_version="${major_version}.${minor_version}.${build_id}_${short_commit_id}"
          jq '.["web-crawler"] = "'"$new_version"'"' manifests/dev.json > manifests/dev.json.tmp
          mv manifests/dev.json.tmp manifests/dev.json
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add manifests/dev.json
          git commit -m "Update web-rawler version in dev.json"
          git push origin main
      - name: Login to Docker registry
        run: |
          echo "LOGIN TO DOCKER REGISTRY"
          docker login docker.pkg.github.com --username dangi13 --password ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build . --file ./dockerfiles/Dockerfile --tag docker.pkg.github.com/web-crawler/leg-versioner/crawler:${new_version} --build-arg username=dangi13 --build-arg password=${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: |
          docker push docker.pkg.github.com/web-crawler/leg-versioner/crawler:${new_version}