name: Update Manifest File

on:
  push:
    branches:
      - master
jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout releases repo
        uses: actions/checkout@v3
        with:
          repository: dangi13/releases
          ref: master
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update manifest.json
        run: |
          jq '.repository_versions["repo_A"] = "'"$GITHUB_SHA"'"' releases/manifests/dev.json > releases/manifests/dev.json.tmp 
          mv releases/manifests/dev.json.tmp releases/manifests/dev.json 

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add releases/manifest.json
          git commit -m "Update repo_A version in manifest.json"
          git push origin main